<!doctype html>
<html lang="en">
 <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="{{ cfg.bootstrap_dir }}/css/bootstrap{{ cfg.min_suffix }}.css">
  <link rel="stylesheet" href="{{ cfg.bootstrap_dir }}/css/bootstrap-theme{{ cfg.min_suffix }}.css">
 </head>
 <body>
	<h1>{{ title }}</h1>

        <script src="{{ cfg.jquery_dir }}/js/jquery{{ cfg.min_suffix }}.js"></script>
        <script src="{{ cfg.bootstrap_dir }}/js/bootstrap{{ cfg.min_suffix }}.js"></script>
 </body>
</html>



